name: scratcher
description: Scratch card widget which temporarily hides content from the user.
homepage: https://github.com/vintage/scratcher

version: 2.2.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint:
  flutter_test:
    sdk: flutter
